TrainingArguments:
  num_train_epochs: 6
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 200
  save_steps: 1e6
  gradient_accumulation_steps: 16
  push_to_hub: False
  report_to: []