artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MorningStarTM/raw-data/raw/main/new-summary.zip
  local_data_file: artifacts/data_ingestion/new-summary.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['train', 'test', 'val']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/
  tokenizer_name: "google/flan-t5-small"


model_trainer: 
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/
  model_ckpt: "google/flan-t5-small"



model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/new_summary
  model_path: artifacts/model_trainer/Flan-T5-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv