artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MorningStarTM/raw-data/raw/main/news_summary.zip
  local_data_file: artifacts/data_ingestion/news_summary.zip
  unzip_dir: artifacts/data_ingestion

